# Generated by Django 3.1.7 on 2021-03-04 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playstore', '0002_auto_20210303_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='appadmin',
            name='downloadLink',
            field=models.CharField(default='other', max_length=150),
        ),
    ]
