# Generated by Django 3.1.7 on 2021-03-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playUsers', '0005_auto_20210303_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='downloaded',
            field=models.JSONField(default=list),
        ),
    ]
