# Generated by Django 3.1.7 on 2021-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playUsers', '0007_auto_20210304_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='downloaded',
            field=models.JSONField(default=list),
        ),
    ]
